# Generated by Django 4.2.4 on 2023-08-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='date',
        ),
    ]
