# Generated by Django 4.2.4 on 2023-08-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todoitem_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='person_name',
        ),
    ]
